from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import torch
from PIL import Image
from transformers import AutoModelForMultimodalLM, AutoProcessor

from backend.vision.prompt import VISION_PROMPT


# ============================================================
# MODEL CONFIGURATION
# ============================================================

MODEL_ID = "Qwen/Qwen3.5-0.8B"

# Limit HTML size because inference is running on CPU
MAX_HTML_LENGTH = 6000

# Maximum number of tokens generated by the model
MAX_NEW_TOKENS = 500


# ============================================================
# VISION ANALYZER
# ============================================================

class VisionAnalyzer:
    """
    OmniSight Vision Analyzer.

    Takes:
        1. Website screenshot
        2. Website HTML

    Sends both to Qwen3.5-0.8B and extracts
    detected UI issues.
    """

    def __init__(
        self,
        model_id: str = MODEL_ID,
    ) -> None:

        self.model_id = model_id

        print("=" * 60)
        print("Loading OmniSight Vision Model")
        print("=" * 60)
        print(f"Model: {model_id}")
        print("Device: CPU")

        # ----------------------------------------------------
        # Load processor
        # ----------------------------------------------------

        self.processor = AutoProcessor.from_pretrained(
            model_id
        )

        # ----------------------------------------------------
        # Load model
        # ----------------------------------------------------

        self.model = AutoModelForMultimodalLM.from_pretrained(
            model_id,
            torch_dtype=torch.float32,
            device_map="cpu",
        )

        self.model.eval()

        print("Vision model loaded successfully.")
        print("=" * 60)


    # ========================================================
    # ANALYZE UI
    # ========================================================

    def analyze(
        self,
        screenshot_path: str,
        html_path: str,
    ) -> dict[str, Any]:

        screenshot_file = Path(
            screenshot_path
        )

        html_file = Path(
            html_path
        )

        # ----------------------------------------------------
        # Validate screenshot
        # ----------------------------------------------------

        if not screenshot_file.exists():

            raise FileNotFoundError(
                f"Screenshot not found: "
                f"{screenshot_file}"
            )

        # ----------------------------------------------------
        # Validate HTML
        # ----------------------------------------------------

        if not html_file.exists():

            raise FileNotFoundError(
                f"HTML file not found: "
                f"{html_file}"
            )

        print("=" * 60)
        print("Starting UI Analysis")
        print("=" * 60)

        print(
            f"Screenshot: {screenshot_file}"
        )

        print(
            f"HTML: {html_file}"
        )

        # ----------------------------------------------------
        # Load image
        # ----------------------------------------------------

        image = Image.open(
            screenshot_file
        ).convert("RGB")

        # ----------------------------------------------------
        # Read HTML
        # ----------------------------------------------------

        html = html_file.read_text(
            encoding="utf-8",
            errors="ignore",
        )

        # ----------------------------------------------------
        # Limit HTML for CPU inference
        # ----------------------------------------------------

        html = html[:MAX_HTML_LENGTH]

        # ----------------------------------------------------
        # Build prompt
        # ----------------------------------------------------

        prompt = (
            VISION_PROMPT
            + "\n\nRAW HTML:\n"
            + html
        )

        # ----------------------------------------------------
        # Build multimodal messages
        # ----------------------------------------------------

        messages = [
            {
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "image": image,
                    },
                    {
                        "type": "text",
                        "text": prompt,
                    },
                ],
            }
        ]

        print("Preparing model input...")

        # ----------------------------------------------------
        # Apply chat template
        # ----------------------------------------------------

        inputs = self.processor.apply_chat_template(
            messages,
            add_generation_prompt=True,
            tokenize=True,
            return_dict=True,
            return_tensors="pt",
        )

        # ----------------------------------------------------
        # Move tensors to CPU
        # ----------------------------------------------------

        inputs = {
            key: value.to("cpu")
            if hasattr(value, "to")
            else value
            for key, value in inputs.items()
        }

        print("Running Qwen3.5-0.8B inference...")
        print("CPU inference may take some time.")

        # ----------------------------------------------------
        # Generate response
        # ----------------------------------------------------

        with torch.no_grad():

            outputs = self.model.generate(
                **inputs,
                max_new_tokens=MAX_NEW_TOKENS,
                do_sample=False,
            )

        # ----------------------------------------------------
        # Remove input tokens
        # ----------------------------------------------------

        input_length = inputs[
            "input_ids"
        ].shape[-1]

        generated_tokens = outputs[
            0
        ][input_length:]

        # ----------------------------------------------------
        # Decode response
        # ----------------------------------------------------

        response = self.processor.decode(
            generated_tokens,
            skip_special_tokens=True,
        ).strip()

        print("=" * 60)
        print("RAW MODEL RESPONSE")
        print("=" * 60)
        print(response)

        # ----------------------------------------------------
        # Parse model response
        # ----------------------------------------------------

        issues = self._parse_response(
            response
        )

        print("=" * 60)
        print(f"Detected Issues: {len(issues)}")
        print("=" * 60)

        # ----------------------------------------------------
        # Return result
        # ----------------------------------------------------

        return {
            "status": "success",
            "model": self.model_id,
            "screenshot": str(
                screenshot_file
            ),
            "html": str(
                html_file
            ),
            "issues": issues,
            "raw_response": response,
        }


    # ========================================================
    # PARSE VLM RESPONSE
    # ========================================================

    def _parse_response(
        self,
        response: str,
    ) -> list[dict[str, Any]]:
        """
        Handles all common model response formats.

        Supported:

        1. {"issues": [...]}

        2. [...]

        3. ```json
           {"issues": [...]}
           ```

        4. ```json
           [...]
           ```
        """

        response = response.strip()

        if not response:

            return [
                {
                    "id": "parse-error",
                    "type": "model-response",
                    "severity": "low",
                    "description": (
                        "The VLM returned an empty response."
                    ),
                    "element": None,
                    "suggested_fix": None,
                }
            ]

        # ----------------------------------------------------
        # Remove Markdown code fences
        # ----------------------------------------------------

        response = re.sub(
            r"^```(?:json)?\s*",
            "",
            response,
            flags=re.IGNORECASE,
        )

        response = re.sub(
            r"\s*```$",
            "",
            response,
            flags=re.IGNORECASE,
        )

        response = response.strip()

        # ====================================================
        # METHOD 1
        # Direct JSON parsing
        # ====================================================

        try:

            data = json.loads(
                response
            )

            # -----------------------------------------------
            # Object:
            # {"issues": [...]}
            # -----------------------------------------------

            if isinstance(data, dict):

                issues = data.get(
                    "issues",
                    [],
                )

                if isinstance(
                    issues,
                    list,
                ):

                    return self._clean_issues(
                        issues
                    )

            # -----------------------------------------------
            # Array:
            # [...]
            # -----------------------------------------------

            if isinstance(data, list):

                return self._clean_issues(
                    data
                )

        except json.JSONDecodeError:

            pass

        # ====================================================
        # METHOD 2
        # Extract JSON object
        # ====================================================

        object_start = response.find("{")
        object_end = response.rfind("}")

        if (
            object_start != -1
            and object_end != -1
            and object_end > object_start
        ):

            json_text = response[
                object_start:
                object_end + 1
            ]

            try:

                data = json.loads(
                    json_text
                )

                if isinstance(
                    data,
                    dict,
                ):

                    issues = data.get(
                        "issues",
                        [],
                    )

                    if isinstance(
                        issues,
                        list,
                    ):

                        return self._clean_issues(
                            issues
                        )

            except json.JSONDecodeError:

                pass

        # ====================================================
        # METHOD 3
        # Extract JSON array
        # ====================================================

        array_start = response.find("[")
        array_end = response.rfind("]")

        if (
            array_start != -1
            and array_end != -1
            and array_end > array_start
        ):

            json_text = response[
                array_start:
                array_end + 1
            ]

            try:

                data = json.loads(
                    json_text
                )

                if isinstance(
                    data,
                    list,
                ):

                    return self._clean_issues(
                        data
                    )

            except json.JSONDecodeError:

                pass

        # ====================================================
        # PARSE ERROR
        # ====================================================

        return [
            {
                "id": "parse-error",
                "type": "model-response",
                "severity": "low",
                "description": (
                    "The VLM response could not "
                    "be parsed as JSON."
                ),
                "element": None,
                "suggested_fix": None,
            }
        ]


    # ========================================================
    # CLEAN ISSUES
    # ========================================================

    def _clean_issues(
        self,
        issues: list[Any],
    ) -> list[dict[str, Any]]:
        """
        Normalizes VLM issue objects so the API
        always returns a predictable structure.
        """

        cleaned: list[
            dict[str, Any]
        ] = []

        for index, issue in enumerate(
            issues,
            start=1,
        ):

            if not isinstance(
                issue,
                dict,
            ):
                continue

            cleaned.append(
                {
                    "id": issue.get(
                        "id",
                        f"issue-{index}",
                    ),
                    "type": issue.get(
                        "type",
                        "unknown",
                    ),
                    "severity": issue.get(
                        "severity",
                        "low",
                    ),
                    "description": issue.get(
                        "description",
                        "",
                    ),
                    "element": issue.get(
                        "element",
                        None,
                    ),
                    "suggested_fix": issue.get(
                        "suggested_fix",
                        None,
                    ),
                }
            )

        return cleaned


# ============================================================
# SINGLETON ANALYZER
# ============================================================

_analyzer: VisionAnalyzer | None = None


# ============================================================
# PUBLIC FUNCTION
# ============================================================

def analyze_ui(
    screenshot_path: str,
    html_path: str,
) -> dict[str, Any]:

    global _analyzer

    if _analyzer is None:

        _analyzer = VisionAnalyzer()

    return _analyzer.analyze(
        screenshot_path=screenshot_path,
        html_path=html_path,
    )


# ============================================================
# DIRECT TEST
# ============================================================

if __name__ == "__main__":

    screenshot = (
        "screenshots/01_home.png"
    )

    html = (
        "outputs/01_home.html"
    )

    result = analyze_ui(
        screenshot_path=screenshot,
        html_path=html,
    )

    print()
    print("=" * 60)
    print("OMNISIGHT VISION ANALYSIS")
    print("=" * 60)

    print(
        json.dumps(
            result,
            indent=2,
            ensure_ascii=False,
        )
    )